export const GET_GITHUBUSER = "GET_GITHUBUSER";
export const GITHUBUSER_ERROR = "GITHUBUSER_ERROR";

export const GET_GITHUBUSER_REPOS = "GET_GITHUBUSER_REPOS";
export const GITHUBUSER_REPOS_ERROR = "GITHUBUSER_REPOS_ERROR";

export const GET_GITHUBUSER_REPO = "GET_GITHUBUSER_REPO";
export const GITHUBUSER_REPO_ERROR = "GET_GITHUBUSER_REPO_ERROR";
